logging:
  file:
    name: logs/BNK_PROJECT.log
  level:
    root: info
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
server:
  port: 8080
  servlet:
    context-path: /bnk
    session:
      timeout: 20m
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: BNK_PROJECT
    version: ${version}
  datasource:
    url: jdbc:oracle:thin:@oracledb1_high?TNS_ADMIN=src/main/resources/wallet
    username: <DB_USERNAME>
    password: <DB_PASSWORD>
    driver-class-name: oracle.jdbc.OracleDriver
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true
