logging:
  file:
    name: logs/BNK_PROJECT.log
  level:
    root: info
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
server:
  port: 8080
  servlet:
    context-path: /bnk
    session:
      timeout: 20m
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: BNK_PROJECT
    version: ${version}
  datasource:
    url: jdbc:oracle:thin:@//3.37.166.16:1522/XEPDB1 
    username: BNK
    password: abc1234!
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: BNK_HikariPool
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 15000
      auto-commit: true
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false



  devtools:
    livereload:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT

  mail:
    host: smtp.gmail.com
    port: 587
    username: bisunesskyu@gmail.com
    password: detvitlhtcjlqtah
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
        - "file:\${file.path}/"

file:
  path: /home/rsa-key-20251117/upload
  upload:
    path: upload

gemini:
  api:
    key: AIzaSyATRg8BRUUPulbzi37fiHJdzBcAf17Xpy8