logging:
  file:
    name: logs/BNK_PROJECT.log
  level:
    root: info
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
server:
  port: 8080
  servlet:
    context-path: /bnk
    session:
      timeout: 20m
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: BNK_PROJECT
    version: ${version}
  datasource:
    url: jdbc:oracle:thin:@oracledb1_high?TNS_ADMIN=src/main/resources/wallet
    username: <DB_USERNAME>
    password: <DB_PASSWORD>
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: BNK_HikariPool
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 15000
      auto-commit: true

  devtools:
    livereload:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
